version: "3"
services:
  my-web-app-db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=sul440
      - POSTGRES_DATABASE=students
  my-web-app:
    build: .
    ports:
      - "80:80"
    depends_on:
      - my-web-app-db